import {
  CropPrice,
  AgriculturalOfficer,
  GovernmentScheme,
  User,
} from './types';
import { format } from 'date-fns';

export const mockUsers: User[] = [
    { id: '1', name: 'Farmer1', email: 'farmer1@example.com', avatarUrl: 'https://picsum.photos/seed/user1/100/100' },
    { id: '2', name: 'Farmer2', email: 'farmer2@example.com', avatarUrl: 'https://picsum.photos/seed/user2/100/100' },
    { id: '3', name: 'Farmer3', email: 'farmer3@example.com', avatarUrl: 'https://picsum.photos/seed/user3/100/100' },
];

export const mockUserPasswords: { [key: string]: string } = {
    '1': 'password123',
    '2': 'password123',
    '3': 'password123',
};

const generatePrice = (base: number) => {
    const modal = base + Math.floor(Math.random() * 400) - 200;
    const min = modal - Math.floor(Math.random() * 200);
    const max = modal + Math.floor(Math.random() * 200);
    return { minPrice: Math.max(100, min), maxPrice: max, modalPrice: modal };
}

export const mockCropPrices: CropPrice[] = [
  { id: '1', name: 'Paddy', variety: 'Basmati', mandi: 'Karnal, Haryana', ...generatePrice(3300), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '2', name: 'Wheat', variety: 'Lokwan', mandi: 'Indore, Madhya Pradesh', ...generatePrice(2100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '3', name: 'Tomato', variety: 'Hybrid', mandi: 'Nashik, Maharashtra', ...generatePrice(1000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '4', name: 'Onion', variety: 'Red', mandi: 'Lasalgaon, Maharashtra', ...generatePrice(1600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '5', name: 'Potato', variety: 'Jyoti', mandi: 'Agra, Uttar Pradesh', ...generatePrice(1000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '6', name: 'Soybean', variety: 'JS-335', mandi: 'Ujjain, Madhya Pradesh', ...generatePrice(4500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '7', name: 'Cotton', variety: 'MCU-5', mandi: 'Guntur, Andhra Pradesh', ...generatePrice(7000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '8', name: 'Maize', variety: 'Hybrid', mandi: 'Davangere, Karnataka', ...generatePrice(2000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '9', name: 'Gram', variety: 'Desi', mandi: 'Akola, Maharashtra', ...generatePrice(5000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '10', name: 'Sugarcane', variety: 'Co-86032', mandi: 'Kolhapur, Maharashtra', ...generatePrice(300), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '11', name: 'Apple', variety: 'Royal Delicious', mandi: 'Shimla, Himachal Pradesh', ...generatePrice(8000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '12', name: 'Banana', variety: 'Robusta', mandi: 'Jalgaon, Maharashtra', ...generatePrice(1200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '13', name: 'Mango', variety: 'Alphonso', mandi: 'Ratnagiri, Maharashtra', ...generatePrice(4000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '14', name: 'Grapes', variety: 'Thompson Seedless', mandi: 'Nashik, Maharashtra', ...generatePrice(4500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '15', name: 'Turmeric', variety: 'Rajapuri', mandi: 'Erode, Tamil Nadu', ...generatePrice(8500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '16', name: 'Chilli', variety: 'Sannam', mandi: 'Guntur, Andhra Pradesh', ...generatePrice(15000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '17', name: 'Mustard', variety: 'Pusa Bold', mandi: 'Alwar, Rajasthan', ...generatePrice(5500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '18', name: 'Barley', variety: 'BH-393', mandi: 'Jaipur, Rajasthan', ...generatePrice(1800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '19', name: 'Lentil', variety: 'IPL-316', mandi: 'Kanpur, Uttar Pradesh', ...generatePrice(6000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '20', name: 'Groundnut', variety: 'Kadiri-7', mandi: 'Anantapur, Andhra Pradesh', ...generatePrice(6500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '21', name: 'Pigeon Pea', variety: 'Maruti', mandi: 'Gulbarga, Karnataka', ...generatePrice(7000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '22', name: 'Sorghum', variety: 'CSH-9', mandi: 'Solapur, Maharashtra', ...generatePrice(2500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '23', name: 'Pearl Millet', variety: 'HHB-67', mandi: 'Hisar, Haryana', ...generatePrice(2200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '24', name: 'Finger Millet', variety: 'GPU-28', mandi: 'Bengaluru, Karnataka', ...generatePrice(3000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '25', name: 'Castor Seed', variety: 'GCH-7', mandi: 'Mehsana, Gujarat', ...generatePrice(6000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '26', name: 'Coriander', variety: 'ACR-1', mandi: 'Ramganj, Rajasthan', ...generatePrice(7500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '27', name: 'Cumin', variety: 'GC-4', mandi: 'Unjha, Gujarat', ...generatePrice(30000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '28', name: 'Fennel', variety: 'RF-125', mandi: 'Sirohi, Rajasthan', ...generatePrice(9000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '29', name: 'Fenugreek', variety: 'RMt-1', mandi: 'Neemuch, Madhya Pradesh', ...generatePrice(6500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '30', name: 'Linseed', variety: 'Neelam', mandi: 'Sagar, Madhya Pradesh', ...generatePrice(5000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '31', name: 'Safflower', variety: 'Bhima', mandi: 'Jalna, Maharashtra', ...generatePrice(5200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '32', name: 'Sesame', variety: 'GT-10', mandi: 'Amreli, Gujarat', ...generatePrice(12000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '33', name: 'Sunflower', variety: 'KBSH-44', mandi: 'Raichur, Karnataka', ...generatePrice(6000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '34', name: 'Brinjal', variety: 'Pusa Purple Long', mandi: 'Varanasi, Uttar Pradesh', ...generatePrice(1500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '35', name: 'Cabbage', variety: 'Golden Acre', mandi: 'Kolar, Karnataka', ...generatePrice(800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '36', name: 'Carrot', variety: 'Pusa Kesar', mandi: 'Ooty, Tamil Nadu', ...generatePrice(2500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '37', name: 'Cauliflower', variety: 'Pusa Snowball K-1', mandi: 'Dehradun, Uttarakhand', ...generatePrice(1200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '38', name: 'Okra', variety: 'Pusa Sawani', mandi: 'Surat, Gujarat', ...generatePrice(2800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '39', name: 'Peas', variety: 'Arkel', mandi: 'Jalandhar, Punjab', ...generatePrice(3500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '40', name: 'Pumpkin', variety: 'Arka Suryamukhi', mandi: 'Kumbakonam, Tamil Nadu', ...generatePrice(700), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '41', name: 'Radish', variety: 'Pusa Chetki', mandi: 'Lucknow, Uttar Pradesh', ...generatePrice(900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '42', name: 'Spinach', variety: 'All Green', mandi: 'Pune, Maharashtra', ...generatePrice(1000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '43', name: 'Ginger', variety: 'Cochin', mandi: 'Kochi, Kerala', ...generatePrice(15000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '44', name: 'Garlic', variety: 'Yamuna Safed', mandi: 'Mandsaur, Madhya Pradesh', ...generatePrice(12000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '45', name: 'Lemon', variety: 'Kagzi', mandi: 'Gondal, Gujarat', ...generatePrice(4000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '46', name: 'Guava', variety: 'Allahabad Safeda', mandi: 'Prayagraj, Uttar Pradesh', ...generatePrice(2500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '47', name: 'Papaya', variety: 'Red Lady', mandi: 'Chittoor, Andhra Pradesh', ...generatePrice(1500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '48', name: 'Pomegranate', variety: 'Bhagwa', mandi: 'Solapur, Maharashtra', ...generatePrice(10000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '49', name: 'Jackfruit', variety: 'Local', mandi: 'Panruti, Tamil Nadu', ...generatePrice(2000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '50', name: 'Coconut', variety: 'West Coast Tall', mandi: 'Kozhikode, Kerala', ...generatePrice(2800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '51', name: 'Paddy', variety: 'Sona Masoori', mandi: 'Raichur, Karnataka', ...generatePrice(2900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '52', name: 'Wheat', variety: 'Sharbati', mandi: 'Bhopal, Madhya Pradesh', ...generatePrice(2800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '53', name: 'Tomato', variety: 'Pusa Ruby', mandi: 'Bengaluru, Karnataka', ...generatePrice(900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '54', name: 'Onion', variety: 'White', mandi: 'Mahuva, Gujarat', ...generatePrice(1400), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '55', name: 'Potato', variety: 'Kufri Bahar', mandi: 'Farrukhabad, Uttar Pradesh', ...generatePrice(950), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '56', name: 'Maize', variety: 'Pioneer 3396', mandi: 'Karimnagar, Telangana', ...generatePrice(2100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '57', name: 'Cotton', variety: 'Bunny', mandi: 'Adilabad, Telangana', ...generatePrice(7200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '58', name: 'Soybean', variety: 'MAUS-71', mandi: 'Latur, Maharashtra', ...generatePrice(4400), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '59', name: 'Mustard', variety: 'RH-30', mandi: 'Bharatpur, Rajasthan', ...generatePrice(5600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '60', name: 'Gram', variety: 'Jaki-9218', mandi: 'Bikaner, Rajasthan', ...generatePrice(5100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '61', name: 'Pigeon Pea', variety: 'Asha', mandi: 'Kalaburagi, Karnataka', ...generatePrice(7100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '62', name: 'Groundnut', variety: 'G20', mandi: 'Rajkot, Gujarat', ...generatePrice(6800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '63', name: 'Apple', variety: 'Fuji', mandi: 'Srinagar, Jammu & Kashmir', ...generatePrice(7500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '64', name: 'Mango', variety: 'Kesar', mandi: 'Junagadh, Gujarat', ...generatePrice(3000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '65', name: 'Banana', variety: 'Grand Naine', mandi: 'Theni, Tamil Nadu', ...generatePrice(1400), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '66', name: 'Grapes', variety: 'Sonaka', mandi: 'Sangli, Maharashtra', ...generatePrice(4000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '67', name: 'Chilli', variety: 'Teja', mandi: 'Warangal, Telangana', ...generatePrice(18000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '68', name: 'Turmeric', variety: 'Salem', mandi: 'Sangli, Maharashtra', ...generatePrice(8000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '69', name: 'Cumin', variety: 'Local', mandi: 'Jodhpur, Rajasthan', ...generatePrice(28000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '70', name: 'Garlic', variety: 'G-282', mandi: 'Kota, Rajasthan', ...generatePrice(11000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '71', name: 'Ginger', variety: 'Nadia', mandi: 'Siliguri, West Bengal', ...generatePrice(14000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '72', name: 'Paddy', variety: 'IR-64', mandi: 'Burdwan, West Bengal', ...generatePrice(1900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '73', name: 'Wheat', variety: 'HD-2967', mandi: 'Ludhiana, Punjab', ...generatePrice(2150), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '74', name: 'Potato', variety: 'Chipsona-1', mandi: 'Jalandhar, Punjab', ...generatePrice(1200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '75', name: 'Onion', variety: 'Pusa Red', mandi: 'Patna, Bihar', ...generatePrice(1500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '76', name: 'Tomato', variety: 'Arka Rakshak', mandi: 'Madanapalle, Andhra Pradesh', ...generatePrice(1100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '77', name: 'Maize', variety: 'Dekalb', mandi: 'Nizamabad, Telangana', ...generatePrice(2050), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '78', name: 'Soybean', variety: 'KDS-726', mandi: 'Amravati, Maharashtra', ...generatePrice(4600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '79', name: 'Cotton', variety: 'Jadoo', mandi: 'Aurangabad, Maharashtra', ...generatePrice(6900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '80', name: 'Lentil', variety: 'WBL-77', mandi: 'Murshidabad, West Bengal', ...generatePrice(5900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '81', name: 'Sugarcane', variety: 'Co-0238', mandi: 'Meerut, Uttar Pradesh', ...generatePrice(350), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '82', name: 'Barley', variety: 'K-551', mandi: 'Mathura, Uttar Pradesh', ...generatePrice(1850), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '83', name: 'Sorghum', variety: 'M-35-1', mandi: 'Vijayapura, Karnataka', ...generatePrice(2600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '84', name: 'Pomegranate', variety: 'Ganesh', mandi: 'Ahmednagar, Maharashtra', ...generatePrice(9000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '85', name: 'Lemon', variety: 'Eureka', mandi: 'Nagpur, Maharashtra', ...generatePrice(4200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '86', 'id': '86', name: 'Okra', variety: 'Arka Anamika', mandi: 'Vijayawada, Andhra Pradesh', ...generatePrice(2700), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '87', name: 'Cabbage', variety: 'Pride of India', mandi: 'Kolkata, West Bengal', ...generatePrice(900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '88', name: 'Cauliflower', variety: 'Early Kunwari', mandi: 'Delhi', ...generatePrice(1300), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '89', name: 'Brinjal', variety: 'Pusa Kranti', mandi: 'Jaipur, Rajasthan', ...generatePrice(1400), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '90', name: 'Peas', variety: 'Bonneville', mandi: 'Una, Himachal Pradesh', ...generatePrice(3800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '91', name: 'Carrot', variety: 'Nantes', mandi: 'Pune, Maharashtra', ...generatePrice(2600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '92', name: 'Radish', variety: 'Japanese White', mandi: 'Nashik, Maharashtra', ...generatePrice(950), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '93', name: 'Guava', variety: 'L-49', mandi: 'Lucknow, Uttar Pradesh', ...generatePrice(2600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '94', name: 'Papaya', variety: 'Pusa Delicious', mandi: 'Pune, Maharashtra', ...generatePrice(1600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '95', name: 'Jackfruit', variety: 'Singapore', mandi: 'Cuddalore, Tamil Nadu', ...generatePrice(2200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '96', name: 'Coconut', variety: 'Tiptur Tall', mandi: 'Tumkur, Karnataka', ...generatePrice(2700), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '97', name: 'Sesame', variety: 'VRI-1', mandi: 'Villupuram, Tamil Nadu', ...generatePrice(12500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '98', name: 'Sunflower', variety: 'Sunbred', mandi: 'Gulbarga, Karnataka', ...generatePrice(6100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '99', name: 'Coriander', variety: 'CO-4', mandi: 'Coimbatore, Tamil Nadu', ...generatePrice(8000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '100', name: 'Castor Seed', variety: 'GCH-4', mandi: 'Banaskantha, Gujarat', ...generatePrice(6200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '101', name: 'Paddy', variety: 'Jaya', mandi: 'Palakkad, Kerala', ...generatePrice(2100), date: format(new Date(), 'yyyy-MM-dd') }
];


export const mockOfficers: AgriculturalOfficer[] = [
  {
    id: '1',
    name: 'Dr. Ramesh Kumar',
    title: 'Chief Agricultural Officer',
    district: 'Thrissur, Kerala',
    phone: '+91-9876543210',
    email: 'ramesh.kumar@gov.in',
    avatarUrl: 'https://picsum.photos/seed/officer1/100/100',
  },
  {
    id: '2',
    name: 'Sunita Sharma',
    title: 'Horticulture Specialist',
    district: 'Pune, Maharashtra',
    phone: '+91-9876543211',
    email: 'sunita.sharma@gov.in',
    avatarUrl: 'https://picsum.photos/seed/officer2/100/100',
  },
  {
    id: '3',
    name: 'Anil Singh',
    title: 'Soil Health Expert',
    district: 'Ludhiana, Punjab',
    phone: '+91-9876543212',
    email: 'anil.singh@gov.in',
    avatarUrl: 'https://picsum.photos/seed/officer3/100/100',
  },
    {
    id: '4',
    name: 'Priya Patel',
    title: 'Pest Management Officer',
    district: 'Anand, Gujarat',
    phone: '+91-9876543213',
    email: 'priya.patel@gov.in',
    avatarUrl: 'https://picsum.photos/seed/officer4/100/100',
  },
];

export const mockSchemes: GovernmentScheme[] = [
  {
    id: '1',
    name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    description:
      'An income support scheme for all landholding farmer families.',
    eligibility: {
      crops: ['All'],
      states: ['All'],
    },
    link: 'https://pmkisan.gov.in/',
  },
  {
    id: '2',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    description: 'A crop insurance scheme to provide financial support to farmers suffering crop loss/damage.',
    eligibility: {
      crops: ['All'],
      states: ['All'],
    },
    link: 'https://pmfby.gov.in/',
  },
  {
    id: '3',
    name: 'National Mission for Sustainable Agriculture (NMSA)',
    description: 'Aims to make agriculture more productive, sustainable, and climate-resilient.',
    eligibility: {
      crops: ['All'],
      states: ['All'],
    },
    link: 'https://nmsa.dac.gov.in/',
  },
    {
    id: '4',
    name: 'Kerala Paddy Procurement Scheme',
    description: 'A state-specific scheme for procuring paddy at a minimum support price.',
    eligibility: {
      crops: ['Paddy'],
      states: ['Kerala'],
    },
    link: 'http://www.supplycokerala.com/paddy-procurement',
  },
];
