import {
  CropPrice,
  AgriculturalOfficer,
  GovernmentScheme,
  FAQ,
} from './types';
import { format } from 'date-fns';

const generatePrice = (base: number) => {
    const modal = base + Math.floor(Math.random() * 400) - 200;
    const min = modal - Math.floor(Math.random() * 200);
    const max = modal + Math.floor(Math.random() * 200);
    return { minPrice: Math.max(100, min), maxPrice: max, modalPrice: modal };
}

export const mockCropPrices: CropPrice[] = [
  { id: '1', name: 'Paddy', variety: 'Basmati', mandi: 'Karnal, Haryana', ...generatePrice(3300), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '2', name: 'Wheat', variety: 'Lokwan', mandi: 'Indore, Madhya Pradesh', ...generatePrice(2100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '3', name: 'Tomato', variety: 'Hybrid', mandi: 'Nashik, Maharashtra', ...generatePrice(1000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '4', name: 'Onion', variety: 'Red', mandi: 'Lasalgaon, Maharashtra', ...generatePrice(1600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '5', name: 'Potato', variety: 'Jyoti', mandi: 'Agra, Uttar Pradesh', ...generatePrice(1000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '6', name: 'Soybean', variety: 'JS-335', mandi: 'Ujjain, Madhya Pradesh', ...generatePrice(4500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '7', name: 'Cotton', variety: 'MCU-5', mandi: 'Guntur, Andhra Pradesh', ...generatePrice(7000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '8', name: 'Maize', variety: 'Hybrid', mandi: 'Davangere, Karnataka', ...generatePrice(2000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '9', name: 'Gram', variety: 'Desi', mandi: 'Akola, Maharashtra', ...generatePrice(5000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '10', name: 'Sugarcane', variety: 'Co-86032', mandi: 'Kolhapur, Maharashtra', ...generatePrice(300), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '11', name: 'Apple', variety: 'Royal Delicious', mandi: 'Shimla, Himachal Pradesh', ...generatePrice(8000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '12', name: 'Banana', variety: 'Robusta', mandi: 'Jalgaon, Maharashtra', ...generatePrice(1200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '13', name: 'Mango', variety: 'Alphonso', mandi: 'Ratnagiri, Maharashtra', ...generatePrice(4000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '14', name: 'Grapes', variety: 'Thompson Seedless', mandi: 'Nashik, Maharashtra', ...generatePrice(4500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '15', name: 'Turmeric', variety: 'Rajapuri', mandi: 'Erode, Tamil Nadu', ...generatePrice(8500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '16', name: 'Chilli', variety: 'Sannam', mandi: 'Guntur, Andhra Pradesh', ...generatePrice(15000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '17', name: 'Mustard', variety: 'Pusa Bold', mandi: 'Alwar, Rajasthan', ...generatePrice(5500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '18', name: 'Barley', variety: 'BH-393', mandi: 'Jaipur, Rajasthan', ...generatePrice(1800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '19', name: 'Lentil', variety: 'IPL-316', mandi: 'Kanpur, Uttar Pradesh', ...generatePrice(6000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '20', name: 'Groundnut', variety: 'Kadiri-7', mandi: 'Anantapur, Andhra Pradesh', ...generatePrice(6500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '21', name: 'Pigeon Pea', variety: 'Maruti', mandi: 'Gulbarga, Karnataka', ...generatePrice(7000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '22', name: 'Sorghum', variety: 'CSH-9', mandi: 'Solapur, Maharashtra', ...generatePrice(2500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '23', name: 'Pearl Millet', variety: 'HHB-67', mandi: 'Hisar, Haryana', ...generatePrice(2200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '24', name: 'Finger Millet', variety: 'GPU-28', mandi: 'Bengaluru, Karnataka', ...generatePrice(3000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '25', name: 'Castor Seed', variety: 'GCH-7', mandi: 'Mehsana, Gujarat', ...generatePrice(6000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '26', name: 'Coriander', variety: 'ACR-1', mandi: 'Ramganj, Rajasthan', ...generatePrice(7500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '27', name: 'Cumin', variety: 'GC-4', mandi: 'Unjha, Gujarat', ...generatePrice(30000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '28', name: 'Fennel', variety: 'RF-125', mandi: 'Sirohi, Rajasthan', ...generatePrice(9000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '29', name: 'Fenugreek', variety: 'RMt-1', mandi: 'Neemuch, Madhya Pradesh', ...generatePrice(6500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '30', name: 'Linseed', variety: 'Neelam', mandi: 'Sagar, Madhya Pradesh', ...generatePrice(5000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '31', name: 'Safflower', variety: 'Bhima', mandi: 'Jalna, Maharashtra', ...generatePrice(5200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '32', name: 'Sesame', variety: 'GT-10', mandi: 'Amreli, Gujarat', ...generatePrice(12000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '33', name: 'Sunflower', variety: 'KBSH-44', mandi: 'Raichur, Karnataka', ...generatePrice(6000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '34', name: 'Brinjal', variety: 'Pusa Purple Long', mandi: 'Varanasi, Uttar Pradesh', ...generatePrice(1500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '35', name: 'Cabbage', variety: 'Golden Acre', mandi: 'Kolar, Karnataka', ...generatePrice(800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '36', name: 'Carrot', variety: 'Pusa Kesar', mandi: 'Ooty, Tamil Nadu', ...generatePrice(2500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '37', name: 'Cauliflower', variety: 'Pusa Snowball K-1', mandi: 'Dehradun, Uttarakhand', ...generatePrice(1200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '38', name: 'Okra', variety: 'Pusa Sawani', mandi: 'Surat, Gujarat', ...generatePrice(2800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '39', name: 'Peas', variety: 'Arkel', mandi: 'Jalandhar, Punjab', ...generatePrice(3500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '40', name: 'Pumpkin', variety: 'Arka Suryamukhi', mandi: 'Kumbakonam, Tamil Nadu', ...generatePrice(700), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '41', name: 'Radish', variety: 'Pusa Chetki', mandi: 'Lucknow, Uttar Pradesh', ...generatePrice(900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '42', name: 'Spinach', variety: 'All Green', mandi: 'Pune, Maharashtra', ...generatePrice(1000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '43', name: 'Ginger', variety: 'Cochin', mandi: 'Kochi, Kerala', ...generatePrice(15000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '44', name: 'Garlic', variety: 'Yamuna Safed', mandi: 'Mandsaur, Madhya Pradesh', ...generatePrice(12000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '45', name: 'Lemon', variety: 'Kagzi', mandi: 'Gondal, Gujarat', ...generatePrice(4000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '46', name: 'Guava', variety: 'Allahabad Safeda', mandi: 'Prayagraj, Uttar Pradesh', ...generatePrice(2500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '47', name: 'Papaya', variety: 'Red Lady', mandi: 'Chittoor, Andhra Pradesh', ...generatePrice(1500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '48', name: 'Pomegranate', variety: 'Bhagwa', mandi: 'Solapur, Maharashtra', ...generatePrice(10000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '49', name: 'Jackfruit', variety: 'Local', mandi: 'Panruti, Tamil Nadu', ...generatePrice(2000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '50', name: 'Coconut', variety: 'West Coast Tall', mandi: 'Kozhikode, Kerala', ...generatePrice(2800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '51', name: 'Paddy', variety: 'Sona Masoori', mandi: 'Raichur, Karnataka', ...generatePrice(2900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '52', name: 'Wheat', variety: 'Sharbati', mandi: 'Bhopal, Madhya Pradesh', ...generatePrice(2800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '53', name: 'Tomato', variety: 'Pusa Ruby', mandi: 'Bengaluru, Karnataka', ...generatePrice(900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '54', name: 'Onion', variety: 'White', mandi: 'Mahuva, Gujarat', ...generatePrice(1400), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '55', name: 'Potato', variety: 'Kufri Bahar', mandi: 'Farrukhabad, Uttar Pradesh', ...generatePrice(950), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '56', name: 'Maize', variety: 'Pioneer 3396', mandi: 'Karimnagar, Telangana', ...generatePrice(2100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '57', name: 'Cotton', variety: 'Bunny', mandi: 'Adilabad, Telangana', ...generatePrice(7200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '58', name: 'Soybean', variety: 'MAUS-71', mandi: 'Latur, Maharashtra', ...generatePrice(4400), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '59', name: 'Mustard', variety: 'RH-30', mandi: 'Bharatpur, Rajasthan', ...generatePrice(5600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '60', name: 'Gram', variety: 'Jaki-9218', mandi: 'Bikaner, Rajasthan', ...generatePrice(5100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '61', name: 'Pigeon Pea', variety: 'Asha', mandi: 'Kalaburagi, Karnataka', ...generatePrice(7100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '62', name: 'Groundnut', variety: 'G20', mandi: 'Rajkot, Gujarat', ...generatePrice(6800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '63', name: 'Apple', variety: 'Fuji', mandi: 'Srinagar, Jammu & Kashmir', ...generatePrice(7500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '64', name: 'Mango', variety: 'Kesar', mandi: 'Junagadh, Gujarat', ...generatePrice(3000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '65', name: 'Banana', variety: 'Grand Naine', mandi: 'Theni, Tamil Nadu', ...generatePrice(1400), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '66', name: 'Grapes', variety: 'Sonaka', mandi: 'Sangli, Maharashtra', ...generatePrice(4000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '67', name: 'Chilli', variety: 'Teja', mandi: 'Warangal, Telangana', ...generatePrice(18000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '68', name: 'Turmeric', variety: 'Salem', mandi: 'Sangli, Maharashtra', ...generatePrice(8000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '69', name: 'Cumin', variety: 'Local', mandi: 'Jodhpur, Rajasthan', ...generatePrice(28000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '70', name: 'Garlic', variety: 'G-282', mandi: 'Kota, Rajasthan', ...generatePrice(11000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '71', name: 'Ginger', variety: 'Nadia', mandi: 'Siliguri, West Bengal', ...generatePrice(14000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '72', name: 'Paddy', variety: 'IR-64', mandi: 'Burdwan, West Bengal', ...generatePrice(1900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '73', name: 'Wheat', variety: 'HD-2967', mandi: 'Ludhiana, Punjab', ...generatePrice(2150), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '74', name: 'Potato', variety: 'Chipsona-1', mandi: 'Jalandhar, Punjab', ...generatePrice(1200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '75', name: 'Onion', variety: 'Pusa Red', mandi: 'Patna, Bihar', ...generatePrice(1500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '76', name: 'Tomato', variety: 'Arka Rakshak', mandi: 'Madanapalle, Andhra Pradesh', ...generatePrice(1100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '77', name: 'Maize', variety: 'Dekalb', mandi: 'Nizamabad, Telangana', ...generatePrice(2050), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '78', name: 'Soybean', variety: 'KDS-726', mandi: 'Amravati, Maharashtra', ...generatePrice(4600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '79', name: 'Cotton', variety: 'Jadoo', mandi: 'Aurangabad, Maharashtra', ...generatePrice(6900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '80', name: 'Lentil', variety: 'WBL-77', mandi: 'Murshidabad, West Bengal', ...generatePrice(5900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '81', name: 'Sugarcane', variety: 'Co-0238', mandi: 'Meerut, Uttar Pradesh', ...generatePrice(350), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '82', name: 'Barley', variety: 'K-551', mandi: 'Mathura, Uttar Pradesh', ...generatePrice(1850), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '83', name: 'Sorghum', variety: 'M-35-1', mandi: 'Vijayapura, Karnataka', ...generatePrice(2600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '84', name: 'Pomegranate', variety: 'Ganesh', mandi: 'Ahmednagar, Maharashtra', ...generatePrice(9000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '85', name: 'Lemon', variety: 'Eureka', mandi: 'Nagpur, Maharashtra', ...generatePrice(4200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '86', 'id': '86', name: 'Okra', variety: 'Arka Anamika', mandi: 'Vijayawada, Andhra Pradesh', ...generatePrice(2700), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '87', name: 'Cabbage', variety: 'Pride of India', mandi: 'Kolkata, West Bengal', ...generatePrice(900), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '88', name: 'Cauliflower', variety: 'Early Kunwari', mandi: 'Delhi', ...generatePrice(1300), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '89', name: 'Brinjal', variety: 'Pusa Kranti', mandi: 'Jaipur, Rajasthan', ...generatePrice(1400), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '90', name: 'Peas', variety: 'Bonneville', mandi: 'Una, Himachal Pradesh', ...generatePrice(3800), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '91', name: 'Carrot', variety: 'Nantes', mandi: 'Pune, Maharashtra', ...generatePrice(2600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '92', name: 'Radish', variety: 'Japanese White', mandi: 'Nashik, Maharashtra', ...generatePrice(950), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '93', name: 'Guava', variety: 'L-49', mandi: 'Lucknow, Uttar Pradesh', ...generatePrice(2600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '94', name: 'Papaya', variety: 'Pusa Delicious', mandi: 'Pune, Maharashtra', ...generatePrice(1600), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '95', name: 'Jackfruit', variety: 'Singapore', mandi: 'Cuddalore, Tamil Nadu', ...generatePrice(2200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '96', name: 'Coconut', variety: 'Tiptur Tall', mandi: 'Tumkur, Karnataka', ...generatePrice(2700), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '97', name: 'Sesame', variety: 'VRI-1', mandi: 'Villupuram, Tamil Nadu', ...generatePrice(12500), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '98', name: 'Sunflower', variety: 'Sunbred', mandi: 'Gulbarga, Karnataka', ...generatePrice(6100), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '99', name: 'Coriander', variety: 'CO-4', mandi: 'Coimbatore, Tamil Nadu', ...generatePrice(8000), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '100', name: 'Castor Seed', variety: 'GCH-4', mandi: 'Banaskantha, Gujarat', ...generatePrice(6200), date: format(new Date(), 'yyyy-MM-dd') },
  { id: '101', name: 'Paddy', variety: 'Jaya', mandi: 'Palakkad, Kerala', ...generatePrice(2100), date: format(new Date(), 'yyyy-MM-dd') }
];


export const mockOfficers: AgriculturalOfficer[] = [
  {
    id: '1',
    name: 'Dr. Ramesh Kumar',
    title: 'Chief Agricultural Officer',
    district: 'Thrissur, Kerala',
    phone: '+91-9876543210',
    email: 'ramesh.kumar@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=RK',
  },
  {
    id: '2',
    name: 'Sunita Sharma',
    title: 'Horticulture Specialist',
    district: 'Pune, Maharashtra',
    phone: '+91-9876543211',
    email: 'sunita.sharma@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=SS',
  },
  {
    id: '3',
    name: 'Anil Singh',
    title: 'Soil Health Expert',
    district: 'Ludhiana, Punjab',
    phone: '+91-9876543212',
    email: 'anil.singh@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=AS',
  },
  {
    id: '4',
    name: 'Priya Patel',
    title: 'Pest Management Officer',
    district: 'Anand, Gujarat',
    phone: '+91-9876543213',
    email: 'priya.patel@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=PP',
  },
  {
    id: '5',
    name: 'Binu Jacob',
    title: 'Agricultural Officer',
    district: 'Kottayam, Kerala',
    phone: '+91-9876543214',
    email: 'binu.jacob@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=BJ',
  },
  {
    id: '6',
    name: 'Asha Menon',
    title: 'Krishi Bhavan Officer',
    district: 'Ernakulam, Kerala',
    phone: '+91-9876543215',
    email: 'asha.menon@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=AM',
  },
  {
    id: '7',
    name: 'Suresh Pillai',
    title: 'Field Officer',
    district: 'Alappuzha, Kerala',
    phone: '+91-9876543216',
    email: 'suresh.pillai@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=SP',
  },
  {
    id: '8',
    name: 'Fatima Beevi',
    title: 'Asst. Director of Agriculture',
    district: 'Kozhikode, Kerala',
    phone: '+91-9876543217',
    email: 'fatima.beevi@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=FB',
  },
  {
    id: '9',
    name: 'Manoj Varghese',
    title: 'Horticulture Supervisor',
    district: 'Idukki, Kerala',
    phone: '+91-9876543218',
    email: 'manoj.varghese@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=MV',
  },
  {
    id: '10',
    name: 'Lakshmi Nair',
    title: 'Agricultural Assistant',
    district: 'Palakkad, Kerala',
    phone: '+91-9876543219',
    email: 'lakshmi.nair@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=LN',
  },
  {
    id: '11',
    name: 'Rajesh P. N.',
    title: 'Soil Conservation Officer',
    district: 'Pathanamthitta, Kerala',
    phone: '+91-9876543220',
    email: 'rajesh.pn@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=RPN',
  },
  {
    id: '12',
    name: 'Deepa Krishnan',
    title: 'Agricultural Officer',
    district: 'Malappuram, Kerala',
    phone: '+91-9876543221',
    email: 'deepa.krishnan@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=DK',
  },
  {
    id: '13',
    name: 'Vinod Kumar',
    title: 'Field Officer',
    district: 'Wayanad, Kerala',
    phone: '+91-9876543222',
    email: 'vinod.kumar@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=VK',
  },
   {
    id: '14',
    name: 'Jaya Sree',
    title: 'Krishi Darshan Program Coordinator',
    district: 'Thiruvananthapuram, Kerala',
    phone: '+91-9876543223',
    email: 'jayasree.tvm@gov.in',
    avatarUrl: 'https://placehold.co/100x100/EFEFEF/AAAAAA&text=JS',
  }
];

export const mockSchemes: GovernmentScheme[] = [
  {
    id: '1',
    name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    description:
      'An income support scheme for all landholding farmer families.',
    eligibility: {
      crops: ['All'],
      states: ['All'],
    },
    link: 'https://pmkisan.gov.in/',
  },
  {
    id: '2',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    description: 'A crop insurance scheme to provide financial support to farmers suffering crop loss/damage.',
    eligibility: {
      crops: ['All'],
      states: ['All'],
    },
    link: 'https://pmfby.gov.in/',
  },
  {
    id: '3',
    name: 'National Mission for Sustainable Agriculture (NMSA)',
    description: 'Aims to make agriculture more productive, sustainable, and climate-resilient.',
    eligibility: {
      crops: ['All'],
      states: ['All'],
    },
    link: 'https://nmsa.dac.gov.in/',
  },
    {
    id: '4',
    name: 'Kerala Paddy Procurement Scheme',
    description: 'A state-specific scheme for procuring paddy at a minimum support price.',
    eligibility: {
      crops: ['Paddy'],
      states: ['Kerala'],
    },
    link: 'http://www.supplycokerala.com/paddy-procurement',
  },
];

export const mockFaqs: FAQ[] = [
    {
        category: 'General',
        question: 'What is Krishi Mitra?',
        answer: 'Krishi Mitra is an AI-powered smart farming assistant designed to help Indian farmers with instant advice, market data, and weather updates.',
    },
    {
        category: 'General',
        question: 'How do I change the language in the app?',
        answer: 'You can change the language by clicking the globe icon in the top header and selecting your preferred language from the dropdown menu.',
    },
    {
        category: 'Crop Doctor',
        question: 'How does the Crop Doctor work?',
        answer: 'You can type your farming problem in the text box. Our AI expert will analyze your question and provide a detailed solution.',
    },
    {
        category: 'Crop Doctor',
        question: 'What kind of questions can I ask the Crop Doctor?',
        answer: 'You can ask about any farming problem, such as crop diseases, pest control, nutrient deficiencies, or irrigation issues.',
    },
    {
        category: 'Scan Crop',
        question: 'How do I use the Scan Crop feature?',
        answer: 'Upload a clear photo of the affected plant part. The AI will analyze the image to identify potential diseases or pests and suggest solutions.',
    },
    {
        category: 'Scan Crop',
        question: 'What is the maximum image size I can upload?',
        answer: 'For best performance, please upload images smaller than 4MB.',
    },
    {
        category: 'Weather',
        question: 'How do I get the weather forecast for my location?',
        answer: 'The weather page shows a default location forecast. Click "Use My Location" and grant permission to get accurate weather for your current area.',
    },
    {
        category: 'Weather',
        question: 'What does the farming recommendation on the weather page mean?',
        answer: 'The AI provides a concise farming tip based on the current weather conditions, like whether it\'s a good day for sowing, irrigating, or applying pesticides.',
    },
    {
        category: 'Market Prices',
        question: 'Where does the market price data come from?',
        answer: 'The prices are mock data for demonstration, but in a real-world scenario, they would be sourced from eNAM and local mandis.',
    },
    {
        category: 'Market Prices',
        question: 'How can I search for a specific crop?',
        answer: 'Use the search bar on the Market Prices page to filter the list by commodity name, variety, or mandi location.',
    },
    {
        category: 'Soil Health',
        question: 'How can I test my soil?',
        answer: 'You can get your soil tested at a local agricultural university or a government soil testing lab. They will provide a soil health card with nutrient information.',
    },
    {
        category: 'Soil Health',
        question: 'What is a Soil Health Card?',
        answer: 'A Soil Health Card provides information on the nutrient status of your soil, along with recommendations for fertilizer application to improve its health and fertility.',
    },
    {
        category: 'Irrigation',
        question: 'What is drip irrigation?',
        answer: 'Drip irrigation is a water-efficient method where water is dripped slowly to the roots of plants, either from above the soil surface or buried below the surface.',
    },
    {
        category: 'Irrigation',
        question: 'When is the best time to water my plants?',
        answer: 'The best time to water plants is early in the morning when temperatures are cooler. This minimizes water loss through evaporation.',
    },
    {
        category: 'Pest Management',
        question: 'What are some natural pesticides?',
        answer: 'Neem oil, garlic spray, and solutions made from chili peppers are common natural pesticides that can help control pests without harming the environment.',
    },
    {
        category: 'Pest Management',
        question: 'What is Integrated Pest Management (IPM)?',
        answer: 'IPM is an environmentally sensitive approach to pest management that combines various methods, including biological control, habitat manipulation, and the use of resistant varieties.',
    },
    {
        category: 'Fertilizers',
        question: 'What is the difference between N, P, and K?',
        answer: 'N (Nitrogen) promotes leaf growth, P (Phosphorus) is vital for root, flower, and fruit development, and K (Potassium) contributes to the overall health and hardiness of the plant.',
    },
    {
        category: 'Fertilizers',
        question: 'What is compost?',
        answer: 'Compost is decomposed organic matter. It is a rich, dark material used to improve soil structure, provide nutrients, and increase moisture retention.',
    },
    {
        category: 'Weed Control',
        question: 'How can I control weeds without chemicals?',
        answer: 'Mulching, manual removal (hand-pulling), and using cover crops are effective non-chemical methods for controlling weeds in your farm.',
    },
    {
        category: 'Weed Control',
        question: 'What is mulching?',
        answer: 'Mulching is the practice of covering the soil around plants with a layer of material (like straw, plastic, or compost) to suppress weeds, conserve moisture, and regulate soil temperature.',
    },
    {
        category: 'Govt. Schemes',
        question: 'How do I apply for PM-KISAN?',
        answer: 'You can apply for the PM-KISAN scheme through its official portal or by visiting your nearest Common Service Centre (CSC).',
    },
    {
        category: 'Govt. Schemes',
        question: 'What is the benefit of PMFBY crop insurance?',
        answer: 'PMFBY provides insurance coverage and financial support to farmers in the event of crop failure due to natural calamities, pests, or diseases.',
    },
    {
        category: 'Crop Rotation',
        question: 'Why is crop rotation important?',
        answer: 'Crop rotation helps to improve soil fertility, control pests and diseases, and reduce soil erosion by not planting the same crop in the same place year after year.',
    },
    {
        category: 'Crop Rotation',
        question: 'What is a good crop rotation for paddy?',
        answer: 'A common rotation for paddy (rice) is to follow it with a legume crop like gram or lentil, which helps to fix nitrogen back into the soil.',
    },
    {
        category: 'Harvesting',
        question: 'When should I harvest my tomatoes?',
        answer: 'Tomatoes are best harvested when they are firm and fully colored (usually red, but this depends on the variety). They should pull from the vine with a slight twist.',
    },
    {
        category: 'Harvesting',
        question: 'How can I reduce post-harvest losses?',
        answer: 'Proper handling, storage in a cool and dry place, and quick transportation to the market can significantly reduce post-harvest losses.',
    },
    {
        category: 'Organic Farming',
        question: 'What is organic farming?',
        answer: 'Organic farming is an agricultural system that uses ecologically based pest controls and biological fertilizers derived largely from animal and plant wastes and nitrogen-fixing cover crops.',
    },
    {
        category: 'Organic Farming',
        question: 'How do I get an organic certification?',
        answer: 'To get an organic certification in India, you need to follow the standards set by the National Programme for Organic Production (NPOP) and get audited by an accredited certification body.',
    },
    {
        category: 'Farm Machinery',
        question: 'Where can I rent farm machinery?',
        answer: 'Many state governments have apps or services for renting farm machinery. You can also check with local Custom Hiring Centers (CHCs).',
    },
    {
        category: 'Farm Machinery',
        question: 'What is a Custom Hiring Center (CHC)?',
        answer: 'CHCs are centers that rent out farm machinery and equipment to farmers who cannot afford to buy their own high-value machines.',
    },
    {
        category: 'Livestock',
        question: 'What is a good feed for dairy cows?',
        answer: 'A balanced feed for dairy cows includes green fodder, dry fodder (straw), and a concentrate mixture of grains, brans, and mineral supplements.',
    },
    {
        category: 'Livestock',
        question: 'How can I prevent diseases in my poultry?',
        answer: 'Regular vaccination, maintaining a clean and dry coop, providing fresh water and feed, and isolating new birds can help prevent poultry diseases.',
    },
    {
        category: 'Horticulture',
        question: 'How do I grow mango trees?',
        answer: 'Mango trees require a sunny location and well-drained soil. They need regular watering during their initial years and protection from frost.',
    },
    {
        category: 'Horticulture',
        question: 'What is pruning and why is it done?',
        answer: 'Pruning is the selective removal of plant parts (like branches or buds) to improve the plant\'s structure, encourage fruit production, and remove dead or diseased wood.',
    },
    {
        category: 'Agroforestry',
        question: 'What is agroforestry?',
        answer: 'Agroforestry is a land-use management system in which trees or shrubs are grown around or among crops or pastureland, creating a more diverse and sustainable ecosystem.',
    },
    {
        category: 'Agroforestry',
        question: 'What are the benefits of agroforestry?',
        answer: 'Benefits include increased biodiversity, improved soil fertility and moisture retention, and additional income from timber and other tree products.',
    },
    {
        category: 'Seed Treatment',
        question: 'Why should I treat seeds before sowing?',
        answer: 'Seed treatment helps to protect the seeds and seedlings from seed- and soil-borne diseases and pests, leading to better germination and a healthier crop.',
    },
    {
        category: 'Seed Treatment',
        question: 'How can I treat seeds organically?',
        answer: 'You can treat seeds with organic solutions like Panchagavya, Beejamrita, or a Trichoderma formulation to protect them from diseases.',
    },
    {
        category: 'Beekeeping',
        question: 'How does beekeeping help in farming?',
        answer: 'Bees are excellent pollinators. Having beehives on your farm can significantly increase the yield of many fruit and vegetable crops.',
    },
    {
        category: 'Beekeeping',
        question: 'What do I need to start beekeeping?',
        answer: 'To start, you will need a beehive, protective clothing (veil, gloves), a smoker, a hive tool, and a colony of bees from a reputable supplier.',
    },
    {
        category: 'Mushroom Cultivation',
        question: 'Is mushroom cultivation profitable?',
        answer: 'Yes, mushroom cultivation can be very profitable as it requires little space and can be harvested multiple times a year. Oyster and button mushrooms are popular choices.',
    },
    {
        category: 'Mushroom Cultivation',
        question: 'What is needed to grow oyster mushrooms?',
        answer: 'Oyster mushrooms can be grown on pasteurized straw or sawdust in a dark, humid room with good ventilation. They grow quickly and can be harvested in a few weeks.',
    },
    {
        category: 'Polyhouse Farming',
        question: 'What is a polyhouse?',
        answer: 'A polyhouse is a structure made of a polyethylene film cover that allows for the cultivation of crops in a controlled environment, protecting them from adverse weather and pests.',
    },
    {
        category: 'Polyhouse Farming',
        question: 'What crops can be grown in a polyhouse?',
        answer: 'High-value crops like colored capsicum, cucumbers, tomatoes, gerbera, and carnations are commonly and profitably grown in polyhouses.',
    },
    {
        category: 'Water Management',
        question: 'What is rainwater harvesting?',
        answer: 'Rainwater harvesting is the collection and storage of rain, rather than allowing it to run off. This stored water can be used for irrigation during dry periods.',
    },
    {
        category: 'Water Management',
        question: 'How can I build a farm pond?',
        answer: 'You can build a farm pond by excavating a piece of land and, if the soil is porous, lining it with a plastic liner or clay. Government schemes often provide subsidies for this.',
    },
    {
        category: 'Climate Change',
        question: 'How does climate change affect farming?',
        answer: 'Climate change can lead to more extreme weather events like droughts and floods, shifts in growing seasons, and increased pressure from pests and diseases.',
    },
    {
        category: 'Climate Change',
        question: 'What is a climate-resilient crop?',
        answer: 'A climate-resilient crop is a variety that can better withstand environmental stresses like drought, heat, or salinity. Examples include certain varieties of millets and sorghum.',
    },
    {
        category: 'Account',
        question: 'I forgot my password. How can I reset it?',
        answer: 'This app does not have a password system. Access is open to everyone.',
    },
    {
        category: 'Account',
        question: 'How do I delete my account?',
        answer: 'There are no user accounts in this application, so no personal data is stored.',
    },
];

    
    